"""Tests for training/preprocessing/feature_pipeline.py."""

from __future__ import annotations

import pytest

from training.preprocessing.feature_definitions import (
    FORBIDDEN_FEATURES,
    MODEL_A_FEATURES,
    MODEL_B_FEATURES,
    MODEL_C_FEATURES,
    MISSINGNESS_FLAG_COLUMNS,
)
from training.preprocessing.feature_pipeline import (
    INFERENCE_RAW_FEATURES_A,
    INFERENCE_RAW_FEATURES_BC,
    PIPELINE_DERIVED_FEATURES,
    check_training_inference_parity,
)


# ---------------------------------------------------------------------------
# Module-level parity check runs at import — these tests confirm it passed
# ---------------------------------------------------------------------------

def test_import_succeeds() -> None:
    # If the module imported without ValueError, parity check passed at import time.
    import training.preprocessing.feature_pipeline  # noqa: F401


def test_check_training_inference_parity_passes() -> None:
    check_training_inference_parity()


# ---------------------------------------------------------------------------
# Model A — raw inputs cover all training features
# ---------------------------------------------------------------------------

def test_model_a_features_fully_covered_by_inference_inputs() -> None:
    available = INFERENCE_RAW_FEATURES_A | PIPELINE_DERIVED_FEATURES
    missing = set(MODEL_A_FEATURES) - available
    assert missing == set(), (
        f"MODEL_A_FEATURES not derivable at inference: {sorted(missing)}"
    )


def test_model_a_starting_price_in_inference_inputs() -> None:
    assert "starting_price" in INFERENCE_RAW_FEATURES_A


def test_model_a_condition_in_inference_inputs() -> None:
    assert "condition" in INFERENCE_RAW_FEATURES_A


# ---------------------------------------------------------------------------
# Models B + C — engagement features are present
# ---------------------------------------------------------------------------

def test_model_b_features_fully_covered_by_inference_inputs() -> None:
    available = INFERENCE_RAW_FEATURES_BC | PIPELINE_DERIVED_FEATURES
    missing = set(MODEL_B_FEATURES) - available
    assert missing == set(), (
        f"MODEL_B_FEATURES not derivable at inference: {sorted(missing)}"
    )


def test_model_c_features_fully_covered_by_inference_inputs() -> None:
    available = INFERENCE_RAW_FEATURES_BC | PIPELINE_DERIVED_FEATURES
    missing = set(MODEL_C_FEATURES) - available
    assert missing == set(), (
        f"MODEL_C_FEATURES not derivable at inference: {sorted(missing)}"
    )


def test_bc_inputs_are_superset_of_a_inputs() -> None:
    assert INFERENCE_RAW_FEATURES_A.issubset(INFERENCE_RAW_FEATURES_BC)


def test_engagement_features_in_bc_not_in_a() -> None:
    bc_only = INFERENCE_RAW_FEATURES_BC - INFERENCE_RAW_FEATURES_A
    assert "total_bids" in bc_only
    assert "views_count" in bc_only
    assert "bid_momentum" in bc_only


# ---------------------------------------------------------------------------
# Pipeline-derived features
# ---------------------------------------------------------------------------

def test_pipeline_derived_matches_missingness_flag_columns() -> None:
    expected = frozenset(f"is_{col}_known" for col in MISSINGNESS_FLAG_COLUMNS)
    assert PIPELINE_DERIVED_FEATURES == expected


def test_pipeline_derived_not_in_inference_raw_a() -> None:
    # Derived features are generated by the pipeline — not sent directly
    overlap = PIPELINE_DERIVED_FEATURES & INFERENCE_RAW_FEATURES_A
    assert overlap == frozenset()


# ---------------------------------------------------------------------------
# No forbidden features in inference inputs
# ---------------------------------------------------------------------------

def test_no_forbidden_features_in_inference_raw_a() -> None:
    leakage = FORBIDDEN_FEATURES & INFERENCE_RAW_FEATURES_A
    assert leakage == frozenset(), (
        f"Forbidden features in Model A inference inputs: {sorted(leakage)}"
    )


def test_no_forbidden_features_in_inference_raw_bc() -> None:
    leakage = FORBIDDEN_FEATURES & INFERENCE_RAW_FEATURES_BC
    assert leakage == frozenset(), (
        f"Forbidden features in Model B/C inference inputs: {sorted(leakage)}"
    )


def test_winning_amount_not_in_any_inference_input() -> None:
    assert "winning_amount" not in INFERENCE_RAW_FEATURES_A
    assert "winning_amount" not in INFERENCE_RAW_FEATURES_BC


def test_auction_id_not_in_any_inference_input() -> None:
    assert "auction_id" not in INFERENCE_RAW_FEATURES_A
    assert "auction_id" not in INFERENCE_RAW_FEATURES_BC


# ---------------------------------------------------------------------------
# Parity check raises on violations (unit test with monkeypatching)
# ---------------------------------------------------------------------------

def test_parity_raises_on_unreachable_feature(monkeypatch) -> None:
    """Simulate adding a feature to MODEL_A that has no inference path."""
    import training.preprocessing.feature_pipeline as fp

    fake_features = list(MODEL_A_FEATURES) + ["ghost_feature_xyz"]
    monkeypatch.setattr(fp, "MODEL_A_FEATURES", fake_features)

    with pytest.raises(ValueError, match="ghost_feature_xyz"):
        fp.check_training_inference_parity()


def test_parity_raises_on_forbidden_inference_input(monkeypatch) -> None:
    """Simulate a forbidden feature (winning_amount) leaking into raw inference inputs."""
    import training.preprocessing.feature_pipeline as fp

    fake_raw = INFERENCE_RAW_FEATURES_A | frozenset({"winning_amount"})
    monkeypatch.setattr(fp, "INFERENCE_RAW_FEATURES_A", fake_raw)

    with pytest.raises(ValueError, match="winning_amount"):
        fp.check_training_inference_parity()
