"""
training/preprocessing/feature_pipeline.py
============================================
Phase 9B — Training / inference feature parity guard.

Declares the raw feature inputs expected by each FastAPI inference endpoint
and verifies at import time that every training feature (from MODEL_A/B/C_FEATURES
in feature_definitions.py) can be derived from those raw inputs — either sent
directly or generated by the sklearn pipeline's MissingnessFlagger step.

If training features diverge from inference inputs (e.g. someone adds a new
feature to MODEL_A_FEATURES but forgets to add it to the Edge Function's
baseFeatures dict), the import raises ValueError immediately — not silently
during a training run or, worse, during live inference.

Canonical raw inputs mirror the Edge Function payloads in:
  supabase/functions/generate-auction-price-estimate/index.ts  (baseFeatures / engagementFeatures)
  supabase/functions/ai-predict-price/index.ts                 (same baseFeatures)
  supabase/functions/ai-bid-forecast/index.ts                  (same engagementFeatures)
"""

from __future__ import annotations

from .feature_definitions import (
    FORBIDDEN_FEATURES,
    MISSINGNESS_FLAG_COLUMNS,
    MODEL_A_FEATURES,
    MODEL_B_FEATURES,
    MODEL_C_FEATURES,
)

# ---------------------------------------------------------------------------
# Raw inputs sent to /predict-price by the Edge Functions (Model A)
# Mirrors `baseFeatures` in generate-auction-price-estimate/index.ts
# ---------------------------------------------------------------------------
INFERENCE_RAW_FEATURES_A: frozenset[str] = frozenset({
    "main_category",
    "sub_category",
    "brand",
    "condition",
    "region",
    "starting_price",
    "fuel_type",
    "transmission",
    "mileage",
    "ownership_history",
    "accident_history",
    "insurance_status",
    "manufacturing_year",
    "asset_age",
    "auction_duration_hours",
    "has_description",
    "has_images",
})

# Raw inputs sent to /predict-winning-bid and /predict-winning-probability (Models B+C)
# Mirrors `engagementFeatures` in generate-auction-price-estimate/index.ts
INFERENCE_RAW_FEATURES_BC: frozenset[str] = INFERENCE_RAW_FEATURES_A | frozenset({
    "total_bids",
    "unique_bidder_count",
    "views_count",
    "bids_per_view_ratio",
    "view_to_bid_ratio",
    "bid_momentum",
    "time_to_first_bid_hours",
    "is_first_bid_quick",
    "days_until_close",
    "bid_acceleration",
    "price_tier",
})

# Features generated by the sklearn MissingnessFlagger from MISSINGNESS_FLAG_COLUMNS.
# These are NOT sent directly; they are derived inside the preprocessing pipeline.
PIPELINE_DERIVED_FEATURES: frozenset[str] = frozenset(
    f"is_{col}_known" for col in MISSINGNESS_FLAG_COLUMNS
)


# ---------------------------------------------------------------------------
# Parity check
# ---------------------------------------------------------------------------

def check_training_inference_parity() -> None:
    """Raise ValueError if any training feature cannot be derived at inference.

    Checks:
      1. Every feature in MODEL_A/B/C_FEATURES is either a raw inference input
         or a feature derived by the sklearn pipeline (MissingnessFlagger).
      2. No FORBIDDEN_FEATURES appear in the raw inference inputs (defense-in-depth
         — feature_definitions.py already checks this for the model matrices,
         but we also verify the inference-side raw inputs here).

    Raises
    ------
    ValueError
        On the first parity or leakage violation found.
    """
    checks: list[tuple[str, list[str], frozenset[str]]] = [
        ("MODEL_A", MODEL_A_FEATURES, INFERENCE_RAW_FEATURES_A),
        ("MODEL_B", MODEL_B_FEATURES, INFERENCE_RAW_FEATURES_BC),
        ("MODEL_C", MODEL_C_FEATURES, INFERENCE_RAW_FEATURES_BC),
    ]

    for model_name, feature_list, raw_inputs in checks:
        available = raw_inputs | PIPELINE_DERIVED_FEATURES
        missing = set(feature_list) - available
        if missing:
            raise ValueError(
                f"Parity violation: {model_name} training features not derivable "
                f"at inference time: {sorted(missing)}. "
                f"Add them to the Edge Function payload or remove from {model_name}_FEATURES."
            )

        leakage = FORBIDDEN_FEATURES & raw_inputs
        if leakage:
            raise ValueError(
                f"Leakage: forbidden column(s) found in {model_name} inference inputs: "
                f"{sorted(leakage)}. Remove them from the Edge Function payload."
            )


check_training_inference_parity()
