from enum import Enum


class ErrorCode(str, Enum):
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_LOAD_FAILED = "MODEL_LOAD_FAILED"
    ARTIFACT_CORRUPT = "ARTIFACT_CORRUPT"
    FEATURE_MISSING = "FEATURE_MISSING"
    FEATURE_INVALID = "FEATURE_INVALID"
    PREDICTION_STORE_FAILED = "PREDICTION_STORE_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
